#!/usr/bin/env sh

RESOURCES="$XDG_CONFIG_HOME/X11/xresources"
WALL="$HOME/Library/Pictures/wall"
WEATHER="$XDG_DATA_HOME/bin/weather"
STATUS="$XDG_DATA_HOME/bin/Status"

systemctl --user import-environment DISPLAY &

dunst &

pgrep mpd > /dev/null || mpd & 

picom -b &

[ -e "$WEATHER" ] && $WEATHER &

[ -e "$STATUS" ] && $STATUS &

[ -f "$RESOURCES" ] && xrdb -merge "$RESOURCES"

[ -e "$WALL" ] && /usr/bin/feh --no-fehbg --bg-scale "$WALL" 

while :; do
	ssh-agent dwm
done

